### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by thePublicer**
Hi Celab, Mr sigma

### CODE REVIEW

**Comment by thePublicer** [comment]
Calebbbbbbbbb!!!!!!!!!!!!!

**Comment by thePublicer** [comment]
Ski********

**Comment by thePublicer** [comment]
I know you that you like Taco Bell

**Comment by calebtb06** [comment]
max pls stop

**Comment by thePublicer** [comment]
okay

**Comment by calebtb06** [comment]
thanks

**Pull request closed without merging**
